### PR TITLE
Turn `status` field of `TransactionReceipt` into error if it signals …

### LINKED ISSUE #46: Failed transactions don’t trigger error
If a submitted transaction fails (for example if the ledger code panics) the client method that was called does not return an error.

Currently the only failure mode for the ledger is really panics or issues with Parity Ethereum. We should use the `status` field of the receipt that is available to the client to return an error and clearly find a way to document how to debug the error.

### PR DESCRIPTION
**Pull request by rockbmb**
Closes #46.

### CODE REVIEW

File: client/src/lib.rs [hunk 1]
```diff
@@ -192,14 +194,22 @@ impl Client {
...
+            .and_then(move |()| {
+                web3::confirm::send_transaction_with_confirmation(
+                    self.web3.transport().clone(),
+                    transaction_request,
+                    poll_interval,
+                    0,
+                )
+            })
+            .and_then(move |tx_receipt| match tx_receipt.status {
+                Some(U64([0])) => futures::future::err(web3::error::Error::InvalidResponse(
```
Comment (rockbmb) [inline client/src/lib.rs]: There's a variety of `web3::error::Error`s, so I chose one that would make some sense. This isn't very relevant, but let me know if you disagree @geigerzaehler .

File: client/src/lib.rs [hunk 2]
```diff
@@ -192,14 +194,22 @@ impl Client {
...
+                    "Transaction receipt `status` field is 0: transaction failure.".to_string(),
+                )),
+                _ => futures::future::result(Ok(tx_receipt)),
```
Comment (geigerzaehler) [inline client/src/lib.rs]: You can simplify this by removing the `futures::future::result` call and replacing `futures::future::err` with `Err`.

File: client/src/lib.rs (hunk 1 above)
Comment (geigerzaehler) [reply client/src/lib.rs]: Ideally we would introduce our own error enum with a case for failed transactions and web3 errors. But it’s ok if you create an issue for that and we proceed with this PR.

**Comment by rockbmb** [comment]
@geigerzaehler I cannot reply to your second comment, I'll do so here: I don't mind doing this as part of this issue :+1:

File: client/src/lib.rs [hunk 3]
```diff
@@ -71,6 +73,13 @@ impl From<std::io::Error> for ReadContractAddressError {
     }
 }
 
+#[derive(Debug)]
+pub enum ClientError {
+    TransactionError(String),
+    Web3Error(web3::error::Error),
+    AccountUnlockingError(String),
```
Comment (rockbmb) [inline client/src/lib.rs]: @geigerzaehler This is for the `TODO` below. I don't mind handling this in a separate PR.

File: client/src/lib.rs [hunk 4]
```diff
@@ -192,14 +201,23 @@ impl Client {
...
+                    transaction_request,
+                    poll_interval,
+                    0,
+                )
+            })
+            .map_err(ClientError::Web3Error)
+            .and_then(move |tx_receipt| match tx_receipt.status {
+                Some(U64([0])) => Err(ClientError::TransactionError(
+                    "Transaction receipt `status` field is 0: transaction failure.".to_string(),
+                )),
```
Comment (geigerzaehler) [inline client/src/lib.rs]: Instead of having a generic transaction error it would be preferable to have a `TransactionFailed` error and have it properly documented. We then could attach the transaction ID to the constructor to simplify debugging.

File: client/src/lib.rs (hunk 3 above)
Comment (geigerzaehler) [reply client/src/lib.rs]: I’m ok with leaving it like it is. But as a rule of thumb it is generally a good idea to avoid adding unused constructors. You don’t gain anything by adding it now but it requires you to explain its existence. Moreover, if it turns out the constructor is not quite what we need you’ll need to change it again.

File: client/src/lib.rs [hunk 5]
```diff
@@ -71,6 +73,13 @@ impl From<std::io::Error> for ReadContractAddressError {
     }
 }
 
+#[derive(Debug)]
+pub enum ClientError {
```
Comment (geigerzaehler) [inline client/src/lib.rs]: It is considered good practice to implement `std::error::Error`. This allows you to control the error message of panics for example and provides a better debugging experience.
